#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls -ld "$PRG" >/dev/null 2>&1
    link=$(ls -L "$PRG" 2>/dev/null | awk '{print $NF}')
    case $link in
        /*) PRG="$link" ;;
        *) PRG="$(dirname "$PRG")/$link" ;;
    esac
done

APP_HOME=$(cd -P "$(dirname "$PRG")" >/dev/null 2>&1 && pwd)
APP_BASE_NAME=$(basename "$0")

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit "${2:-1}"
}

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi

    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" 1
    fi
else
    JAVACMD=java
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." 1
fi

if [ -z "$ANDROID_SDK_ROOT" ] && [ -z "$ANDROID_HOME" ] && [ ! -f "$APP_HOME/local.properties" ]; then
    ANDROID_SDK_ROOT="$APP_HOME/.android-sdk"
    ANDROID_HOME="$ANDROID_SDK_ROOT"
    export ANDROID_SDK_ROOT ANDROID_HOME

    SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
    if [ ! -x "$SDKMANAGER" ]; then
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"

        TOOLS_ZIP="$ANDROID_SDK_ROOT/cmdline-tools.zip"
        TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"

        if command -v curl >/dev/null 2>&1; then
            curl -fsSL -o "$TOOLS_ZIP" "$TOOLS_URL" || die "ERROR: Failed to download Android command line tools." 1
        elif command -v wget >/dev/null 2>&1; then
            wget -qO "$TOOLS_ZIP" "$TOOLS_URL" || die "ERROR: Failed to download Android command line tools." 1
        else
            die "ERROR: curl or wget is required to download the Android SDK." 1
        fi

        unzip -q "$TOOLS_ZIP" -d "$ANDROID_SDK_ROOT/cmdline-tools" || die "ERROR: Failed to extract Android command line tools." 1
        rm -f "$TOOLS_ZIP"

        if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" ] && [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
            mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        fi

        SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
    fi

    if [ -x "$SDKMANAGER" ]; then
        yes | "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" --licenses >/dev/null 2>&1 || true
        "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-34" "build-tools;34.0.0" >/dev/null
    fi

    if [ ! -f "$APP_HOME/local.properties" ]; then
        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$APP_HOME/local.properties"
    fi
fi

# Increase the maximum file descriptors if we can.
if [ "$(uname 2>/dev/null)" = "Linux" ] ; then
    MAX_FD=$(ulimit -H -n 2>/dev/null)
    if [ $? -eq 0 ] ; then
        ulimit -n "$MAX_FD" 2>/dev/null || warn "Could not set maximum file descriptor limit to $MAX_FD"
    fi
fi

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Collect all arguments for the java command.
# shellcheck disable=SC2086
exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
